// This file is automatically generated by JSDoc;
DocsData = {
  "Accounts": {
    "comment": "/**\n * @namespace Accounts\n * @summary The namespace for all accounts-related methods.\n */",
    "meta": {
      "range": [
        0,
        90
      ],
      "filename": "accounts_common.js",
      "lineno": 1,
      "path": "/Users/sashko/git/meteor/packages/accounts-base",
      "code": {}
    },
    "kind": "namespace",
    "name": "Accounts",
    "summary": "The namespace for all accounts-related methods.",
    "longname": "Accounts",
    "___id": "T000002R000046",
    "___s": true
  },
  "Meteor": {
    "absoluteUrl": {
      "comment": "/**\n * @summary Generate an absolute URL pointing to the application. The server reads from the `ROOT_URL` environment variable to determine where it is running. This is taken care of automatically for apps deployed with `meteor deploy`, but must be provided when using `meteor bundle`.\n * @locus Anywhere\n * @param {String} [path] A path to append to the root URL. Do not include a leading \"`/`\".\n * @param {Object} options\n * @param {Boolean} options.secure Create an HTTPS URL.\n * @param {Boolean} options.replaceLocalhost Replace localhost with 127.0.0.1. Useful for services that don't recognize localhost as a domain name.\n * @param {String} options.rootUrl Override the default ROOT_URL from the server environment. For example: \"`http://foo.example.com`\"\n */",
      "meta": {
        "range": [
          767,
          1901
        ],
        "filename": "url_common.js",
        "lineno": 10,
        "path": "/Users/sashko/git/meteor/packages/meteor",
        "code": {
          "id": "astnode100386274",
          "name": "Meteor.absoluteUrl",
          "type": "FunctionExpression",
          "value": "function",
          "paramnames": [
            "path",
            "options"
          ]
        },
        "vars": {
          "options": null,
          "path": null,
          "url": null
        }
      },
      "summary": "Generate an absolute URL pointing to the application. The server reads from the `ROOT_URL` environment variable to determine where it is running. This is taken care of automatically for apps deployed with `meteor deploy`, but must be provided when using `meteor bundle`.",
      "tags": [
        {
          "originalTitle": "locus",
          "title": "locus",
          "text": "Anywhere",
          "value": "Anywhere"
        }
      ],
      "params": [
        {
          "type": {
            "names": [
              "String"
            ]
          },
          "optional": true,
          "description": "<p>A path to append to the root URL. Do not include a leading &quot;<code>/</code>&quot;.</p>",
          "name": "path"
        },
        {
          "type": {
            "names": [
              "Object"
            ]
          },
          "name": "options"
        }
      ],
      "name": "absoluteUrl",
      "longname": "Meteor.absoluteUrl",
      "kind": "function",
      "memberof": "Meteor",
      "scope": "static",
      "___id": "T000002R066092",
      "___s": true,
      "options": [
        {
          "type": {
            "names": [
              "Boolean"
            ]
          },
          "description": "<p>Create an HTTPS URL.</p>",
          "name": "secure"
        },
        {
          "type": {
            "names": [
              "Boolean"
            ]
          },
          "description": "<p>Replace localhost with 127.0.0.1. Useful for services that don't recognize localhost as a domain name.</p>",
          "name": "replaceLocalhost"
        },
        {
          "type": {
            "names": [
              "String"
            ]
          },
          "description": "<p>Override the default ROOT_URL from the server environment. For example: &quot;<code>http://foo.example.com</code>&quot;</p>",
          "name": "rootUrl"
        }
      ],
      "locus": "Anywhere"
    }
  }
};