root: true # ignore config in main folder

parserOptions:
  ecmaVersion: 2024
  sourceType: module

extends:
  - prettier

env:
  node: true
  mocha: true
  es2024: true

plugins:
  - prettier

rules:
  prettier/prettier: ['error', { 'trailingComma': 'es5', 'singleQuote': true }]
  semi: ['error', 'always']
  global-require: 0
