# Configuration for probot-stale - https://github.com/probot/stale
daysUntilStale: 32
daysUntilClose: 8
exemptLabels:
  - pinned
  - security
  - confirmed
staleLabel: stale-bot
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: >
  This issue has been automatically closed it has not had recent activity.
only: issues

