// Template function for rendering the boilerplate html for cordova
// Replicates the template defined in boilerplate_web.cordova.html
// Arguments: root : { htmlAttributes, css : [{ url }], bundledJsCssUrlRewriteHook : Function, head, dynamicHead, body, dynamicBody, inlineScriptsAllowed, additionalStaticJs, meteorRuntimeConfig }

function escapeAttr(attr) {
  // XXX Technically, we only need to escape ['<', '"'] in attribute mode
  // For simplicity, we fall back onto _.template's html escaping, and escape ['&', '<', '>', '"', "'"] regardless of context
  // Most browsers seem to handle 'over-escaping' gracefully
  return _.template('<%- attr %>')({ attr });
}

function escapeURL(url) {
  // XXX Do we need to do anything here? It's possible that the URL may be escaped already
  return url;
}

export default function(manifest) {
  const root = manifest;
  // XXX do we need to do some validation on the properties of root?
  return [].concat(
    [
      '<html' +_.map(root.htmlAttributes, (value, key) =>
        _.template(' <%= attrName %>="<%= attrValue %>"')({
          attrName: key,
          attrValue: escapeAttr(value)
        })
      ).join('') + '>',
      '<head>'
    ],

    _.map(root.css, ({url}) =>
      _.template('  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="<%= href %>">')({
        href: escapeAttr(escapeURL(root.bundledJsCssUrlRewriteHook(url)))
      })
    ),

    [
      root.head,
      root.dynamicHead,
      '</head>',
      '<body>',
      root.body,
      root.dynamicBody,
      '',
      _.template(root.inlineScriptsAllowed
        ? '  <script type="text/javascript"><%= contents %></script>'
        : '  <script type="text/javascript" src="<%= src %>"></script>'
      )({
        // maybe using another template here is overkill...
        contents: _.template('__meteor_runtime_config__ = JSON.parse(decodeURIComponent(<%= conf %>))')({
          conf: root.meteorRuntimeConfig // XXX why is this a URI?
        }),
        src: escapeAttr(escapeURL(root.rootUrlPathPrefix + '/meteor_runtime_config.js'))
      }),
      ''
    ],

    _.map(root.js, ({url}) =>
      _.template('  <script type="text/javascript" src="<%= src %>"></script>')({
        src: escapeAttr(escapeURL(root.bundledJsCssUrlRewriteHook(url)))
      })
    ),

    _.map(root.additionalStaticJs, ({contents, pathname}) => (
      _.template(root.inlineScriptsAllowed
        ? '  <script><%= contents %></script>'
        : '  <script type="text/javascript" src="<%= src %>"></script>'
      )({
        contents: contents,
        src: escapeAttr(escapeURL(root.rootUrlPathPrefix + pathname))
      })
    )),

    [
      '', '',
      '</body>',
      '</html>'
    ],

    ['', '<!-- Generated by boilerplate generator -->'] // to help distinguish old generator from new
  ).join('\n');
}

