// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "3.7"
#define szVerMajorMinorBuildRev "3.7.5533.1995"
#define rmj	3
#define rmm	7
#define rbd	5533
#define rev	1995
#define szVerName	"BalExtensionExt Release"

#endif
