exports.MESSAGE_FROM_PARENT = "MESSAGE_FROM_PARENT";
exports.RESPONSE_FROM_PARENT = "RESPONSE_FROM_PARENT";
exports.MESSAGE_FROM_CHILD = "MESSAGE_FROM_CHILD";
exports.RESPONSE_FROM_CHILD = "RESPONSE_FROM_CHILD";
exports.CHILD_READY = "CHILD_READY";

