const fs = require('fs');
const path = require('path');

const toPosix = value => value.split(path.sep).join('/');

// Keep Blaze compilation in Meteor, but preserve Rspack's sync/async boundary.
// Each async chunk waits for Meteor to fetch and evaluate its HTML dependencies.
class BlazeTemplatesPlugin {
  constructor({ projectDir, filePath }) {
    this.filePath = path.resolve(projectDir, filePath);
    this.moduleId = '/' + toPosix(path.relative(projectDir, this.filePath));
  }

  apply(compiler) {
    const pluginName = 'BlazeTemplatesPlugin';
    const { RuntimeGlobals, RuntimeModule } = compiler.webpack;
    const bridgeModuleId = this.moduleId;

    class BlazeTemplatesRuntimeModule extends RuntimeModule {
      constructor() {
        super('Meteor Blaze templates', RuntimeModule.STAGE_ATTACH);
      }

      generate() {
        return `${RuntimeGlobals.ensureChunkHandlers}.blaze = function(chunkId, promises) {
  var pending = require(${JSON.stringify(bridgeModuleId)}).load(chunkId);
  if (pending) promises.push(pending);
};`;
      }
    }

    compiler.hooks.thisCompilation.tap(pluginName, compilation => {
      compilation.hooks.runtimeRequirementInTree
        .for(RuntimeGlobals.ensureChunkHandlers)
        .tap(pluginName, chunk => {
          compilation.addRuntimeModule(chunk, new BlazeTemplatesRuntimeModule());
        });
    });

    // Write before RequireExternalsPlugin links this bridge into Meteor's entry.
    compiler.hooks.done.tap({ name: pluginName, stage: -20 }, stats => {
      if (stats.hasErrors()) return;
      const { compilation } = stats;
      const eager = new Set();
      const asyncChunks = new Map();
      for (const chunk of compilation.chunks) {
        const templates = new Set();
        for (const module of compilation.chunkGraph.getChunkModulesIterable(chunk)) {
          const resource = module.resource?.split('?')[0];
          if (resource && /\.html$/i.test(resource)) templates.add(resource);
        }
        if (chunk.canBeInitial()) {
          for (const template of templates) eager.add(template);
        } else if (templates.size) {
          asyncChunks.set(chunk.id, templates);
        }
      }

      const importPath = resource => {
        const relative = toPosix(path.relative(path.dirname(this.filePath), resource));
        return JSON.stringify(relative.startsWith('.') ? relative : './' + relative);
      };
      const lines = [
        '// Generated by BlazeTemplatesPlugin. Do not edit.',
        // Blaze uses Meteor's reload so the JS chunk and its compiled templates
        // change together. Also invalidate this entry for JS-only rebuilds.
        `// Rspack build: ${stats.hash}`,
        ...[...eager].sort().map(resource => `import ${importPath(resource)};`),
        '',
        'exports.require = function(id) { return require(id); };',
        'exports.load = function(chunkId) {',
        '  switch (chunkId) {',
      ];
      for (const [chunkId, templates] of [...asyncChunks].sort(([a], [b]) => String(a).localeCompare(String(b)))) {
        const lazy = [...templates].filter(resource => !eager.has(resource)).sort();
        if (lazy.length) {
          lines.push(`    case ${JSON.stringify(chunkId)}: return Promise.all([${
            lazy.map(resource => `import(${importPath(resource)})`).join(', ')
          }]);`);
        }
      }
      lines.push('  }', '};', '');
      const source = lines.join('\n');
      if (!fs.existsSync(this.filePath) || fs.readFileSync(this.filePath, 'utf8') !== source) {
        fs.mkdirSync(path.dirname(this.filePath), { recursive: true });
        fs.writeFileSync(this.filePath, source);
      }
    });
  }
}

module.exports = { BlazeTemplatesPlugin };
