// ESM Loader for Meteor server bundles
//
// Alternative to the legacy boot chain (boot.js + runtime.js + npm-require.js).
// Loads Meteor packages via standard ESM dynamic imports instead of
// vm.runInThisContext, eliminating the need for Reify and Module.prototype
// patching.
//
// Generated by `meteor build --format=esm`. Not used by the legacy format.
//
// Usage:
//   import { boot } from './esm-loader.mjs';
//   await boot('/path/to/bundle/programs/server');

import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import { AsyncLocalStorage } from 'node:async_hooks';
import path from 'node:path';
import fs from 'node:fs';

// ============================================================
// Resolver
//
// Maps npm require calls from Meteor packages to their actual
// locations on disk. Each package may have its own node_modules
// directory; the resolver uses program.json to build a per-package
// search path.
// ============================================================

const asyncPackageContext = new AsyncLocalStorage();

function createResolver(serverDir, programJson) {
  const require = createRequire(path.join(serverDir, '_virtual.js'));

  const packageNodeModulesMap = {};
  const packageOwnNodeModulesMap = {};
  for (const item of programJson.load) {
    const dirs = [];
    if (typeof item.node_modules === 'string') {
      dirs.push(path.join(serverDir, item.node_modules));
      packageOwnNodeModulesMap[item.path] = true;
    } else if (item.node_modules && typeof item.node_modules === 'object') {
      for (const p of Object.keys(item.node_modules)) {
        if (!item.node_modules[p].local) dirs.push(path.join(serverDir, p));
      }
      packageOwnNodeModulesMap[item.path] = true;
    }
    dirs.push(path.join(serverDir, 'node_modules'));
    packageNodeModulesMap[item.path] = dirs;
  }

  const packageMatchers = [];
  let appMatcher = null;

  for (const item of programJson.load) {
    const kp = item.path;
    const patterns = [kp];
    if (kp.startsWith('packages/') && kp.endsWith('.js')) {
      const base = kp.slice(0, -3); // e.g. 'packages/ddp-server' or 'packages/ostrio_flow-router-extra'
      patterns.push(base + '/');
      const pkgName = base.slice(9); // e.g. 'ddp-server' or 'ostrio_flow-router-extra'
      patterns.push('node_modules/meteor/' + pkgName + '/');
      if (pkgName.includes('_')) {
        patterns.push('node_modules/meteor/' + pkgName.replace(/_/g, ':') + '/');
        patterns.push('packages/' + pkgName.replace(/_/g, ':') + '/');
      }
      packageMatchers.push({ path: kp, patterns });
    } else if (kp === 'app/app.js') {
      patterns.push(
        path.join(serverDir, 'app') + '/',
        'programs/server/app/',
        'meteor://\u{1F4BB}app',
        'meteor://%F0%9F%92%BBapp',
        'app/app.js'
      );
      appMatcher = { path: kp, patterns };
    } else {
      if (kp.endsWith('.js')) {
        patterns.push(kp.slice(0, -3) + '/');
      }
      packageMatchers.push({ path: kp, patterns });
    }
  }
  if (appMatcher) {
    packageMatchers.push(appMatcher);
  }

  let currentPackagePath = null;

  function resolveInDirs(name, dirs) {
    for (const dir of dirs) {
      try {
        return createRequire(path.join(dir, '_v.js')).resolve(name);
      } catch (e) { continue; }
    }
    return null;
  }

  function getCallerPackagePath() {
    const store = asyncPackageContext.getStore();
    if (store && store.packagePath) return store.packagePath;

    const stack = new Error().stack || '';
    for (const rawLine of stack.split('\n')) {
      if (rawLine.includes('esm-loader.mjs') || rawLine.includes('core-runtime.js') || rawLine.includes('node:') || rawLine.includes('native:')) {
        continue;
      }
      let line = rawLine;
      try { line = decodeURIComponent(rawLine); } catch (e) {}
      for (const matcher of packageMatchers) {
        for (const pat of matcher.patterns) {
          if (line.includes(pat) || rawLine.includes(pat)) return matcher.path;
        }
      }
    }
    return currentPackagePath;
  }

  function getDirs() {
    const pkgPath = getCallerPackagePath();
    if (pkgPath && packageNodeModulesMap[pkgPath]) {
      return packageNodeModulesMap[pkgPath];
    }
    return [path.join(serverDir, 'node_modules')];
  }

  function meteorNpmRequire(name, error) {
    const dirs = getDirs();

    // Virtual absolute paths: /node_modules/meteor/X/node_modules/Y
    if (name.startsWith('/node_modules/')) {
      const parts = name.split('/node_modules/');
      const lastPart = parts[parts.length - 1];
      const resolved = resolveInDirs(lastPart, dirs);
      if (resolved) return require(resolved);
      const diskPath = path.join(serverDir, 'npm' + name);
      if (fs.existsSync(diskPath)) return require(diskPath);
    }

    // Normal module names in caller's search path
    const resolved = resolveInDirs(name, dirs);
    if (resolved) return require(resolved);

    // Node builtins
    try { return require(name); } catch (e) {}

    throw error || new Error('Cannot find module ' + JSON.stringify(name));
  }

  meteorNpmRequire.resolve = function (name) {
    const dirs = getDirs();
    if (name.startsWith('/node_modules/')) {
      const parts = name.split('/node_modules/');
      const lastPart = parts[parts.length - 1];
      const resolved = resolveInDirs(lastPart, dirs);
      if (resolved) return resolved;
      const diskPath = path.join(serverDir, 'npm' + name);
      if (fs.existsSync(diskPath)) return diskPath;
    }
    const resolved = resolveInDirs(name, dirs);
    if (resolved) return resolved;

    return require.resolve(name);
  };

  return {
    meteorNpmRequire,
    getCallerPackagePath,
    setCurrentPackage(p) { currentPackagePath = p; },
    getCurrentPackage() { return currentPackagePath; },
    packageNodeModulesMap,
    packageOwnNodeModulesMap,
  };
}

// ============================================================
// Boot
//
// Three entry points:
//   boot(serverDir)         — full boot: load packages + run main (default)
//   bootPackages(serverDir) — load packages only, return before main()
//   runMain()               — run startup hooks + main() (call after bootPackages)
//
// bootPackages + runMain exist so that a custom host (e.g. Bun.serve)
// can inject setup between package loading and app startup.
// ============================================================

/**
 * Load all Meteor packages and setup globals, but do NOT run main().
 * Returns context needed by custom hosts.
 */
export async function bootPackages(serverDir) {
  const programJson = JSON.parse(fs.readFileSync(path.join(serverDir, 'program.json'), 'utf8'));
  const configJson = JSON.parse(fs.readFileSync(path.join(serverDir, 'config.json'), 'utf8'));
  const buildDir = path.dirname(path.dirname(serverDir));
  const starJson = JSON.parse(fs.readFileSync(path.join(buildDir, 'star.json'), 'utf8'));
  const programsDir = path.dirname(serverDir);

  const { meteorNpmRequire, getCallerPackagePath, setCurrentPackage, getCurrentPackage, packageNodeModulesMap, packageOwnNodeModulesMap } = createResolver(serverDir, programJson);

  // Build per-package asset maps from program.json
  // In the legacy boot, Assets is injected per-package via closure.
  // Here, we use a global Assets object that switches context per-package,
  // same pattern as the resolver's setCurrentPackage.
  const packageAssetsMap = {};
  for (const item of programJson.load) {
    if (item.assets) {
      packageAssetsMap[item.path] = item.assets;
    }
  }
  let currentAssets = null;

  function setCurrentAssets(packagePath) {
    currentAssets = packageAssetsMap[packagePath] || null;
  }

  function packageHasCustomEnv(packagePath) {
    if (!packagePath) return false;
    if (packageAssetsMap[packagePath] && Object.keys(packageAssetsMap[packagePath]).length > 0) return true;
    if (packageOwnNodeModulesMap && packageOwnNodeModulesMap[packagePath]) return true;
    return false;
  }

  // Path normalization matching boot.js behavior (via mini-files.ts)
  function normalizeAssetPath(assetPath) {
    if (process.platform === 'win32') {
      assetPath = assetPath.replace(/\\/g, '/');
    }
    return assetPath ? assetPath.normalize('NFC') : assetPath;
  }

  // Globals expected by Meteor packages
  globalThis.__meteor_bootstrap__ = {
    startupHooks: [],
    serverDir,
    configJson,
    isFibersDisabled: true,
  };
  globalThis.__meteor_runtime_config__ = {
    meteorRelease: configJson.meteorRelease,
    gitCommitHash: starJson.gitCommitHash,
  };
  if (!process.env.APP_ID) process.env.APP_ID = configJson.appId;

  globalThis.Npm = { require: meteorNpmRequire };

  function resolveAssetEntry(assetPath) {
    assetPath = normalizeAssetPath(assetPath);
    const callerPath = getCallerPackagePath();
    if (callerPath && packageAssetsMap[callerPath] && packageAssetsMap[callerPath][assetPath]) {
      return packageAssetsMap[callerPath][assetPath];
    }
    if (currentAssets && currentAssets[assetPath]) {
      return currentAssets[assetPath];
    }
    const appAssets = packageAssetsMap['app/app.js'];
    if (appAssets && (!callerPath || callerPath === 'app/app.js') && appAssets[assetPath]) {
      return appAssets[assetPath];
    }
    return null;
  }

  // Assets API — reads real files from the bundle, per-package context
  globalThis.Assets = {
    getTextAsync(assetPath, callback) {
      return getAsset(assetPath, 'utf8', callback);
    },
    getBinaryAsync(assetPath, callback) {
      return getAsset(assetPath, undefined, callback);
    },
    absoluteFilePath(assetPath) {
      const relPath = resolveAssetEntry(assetPath);
      if (!relPath) {
        throw new Error('Unknown asset: ' + assetPath);
      }
      return path.join(serverDir, relPath);
    },
    getServerDir() { return serverDir; },
  };

  function getAsset(assetPath, encoding, callback) {
    const relPath = resolveAssetEntry(assetPath);
    if (!relPath) {
      const err = new Error('Unknown asset: ' + assetPath);
      if (callback) { callback(err); return; }
      return Promise.reject(err);
    }
    const filePath = path.join(serverDir, relPath);
    if (callback) {
      fs.readFile(filePath, encoding, (err, result) => {
        if (err) { callback(err); return; }
        callback(null, encoding ? result : new Uint8Array(result));
      });
      return;
    }
    return fs.promises.readFile(filePath, encoding).then(result =>
      encoding ? result : new Uint8Array(result)
    );
  }

  globalThis.npmRequire = meteorNpmRequire;
  globalThis.Profile = function (name, fn) { return fn || function () {}; };
  globalThis.Profile.time = function (name, fn) { return fn(); };
  globalThis.Profile.run = async function (name, fn) { return fn(); };

  globalThis.__METEOR_ASYNC_LOCAL_STORAGE = new AsyncLocalStorage();

  // Enable native source maps (Node 20+)
  if (typeof process.setSourceMapsEnabled === 'function') {
    process.setSourceMapsEnabled(true);
  }

  // Dynamic import info for the dynamic-import package
  globalThis.dynamicImportInfo = { server: { dynamicRoot: path.join(serverDir, 'dynamic') } };
  const clientArchs = configJson.clientArchs || Object.keys(configJson.clientPaths || {});
  clientArchs.forEach(arch => {
    globalThis.dynamicImportInfo[arch] = { dynamicRoot: path.join(programsDir, arch, 'dynamic') };
  });

  // The Meteor linker generates implicit global assignments
  // (e.g. `Mongo = Package.mongo.Mongo`) which are illegal in ESM strict mode.
  // Pre-declare them on globalThis to avoid ReferenceError.
  for (const dir of [path.join(serverDir, 'packages'), path.join(serverDir, 'app')]) {
    if (!fs.existsSync(dir)) continue;
    for (const file of fs.readdirSync(dir).filter(f => f.endsWith('.js'))) {
      const src = fs.readFileSync(path.join(dir, file), 'utf8');
      for (const m of src.matchAll(/^(\w+)\s*=\s*Package/gm)) {
        if (!(m[1] in globalThis)) globalThis[m[1]] = undefined;
      }
    }
  }

  // Map core-runtime queue names to program.json load paths. Packages queue
  // under their own name ('ddp-server'); the app queues under the string "null".
  const queuePathByName = Object.create(null);
  for (const item of programJson.load) {
    const m = /^packages\/(.+)\.js$/.exec(item.path);
    if (m) {
      queuePathByName[m[1]] = item.path;
      if (m[1].includes('_')) {
        queuePathByName[m[1].replace(/_/g, ':')] = item.path;
      }
    } else if (item.path === 'app/app.js') {
      queuePathByName['null'] = item.path;
    }
  }
  const appPath = queuePathByName['null'] || null;

  // core-runtime defers package initialization into a queue drained AFTER the
  // import loop below, so binding npm/asset resolution around import() is not
  // enough: by the time a package's eager modules run, the loop has moved on
  // and Npm.require() would resolve against the last package imported.
  // Wrap queue() so the binding happens when a package's initialization starts.
  // processNext() is strictly sequential (guarded by isProcessing), so the
  // binding stays correct for the whole package, async eager modules included.
  const boundFunctionCache = new WeakMap();
  function bindPackageFunction(fn, itemPath) {
    if (typeof fn !== 'function' || fn.__pkgBound) return fn;
    let cached = boundFunctionCache.get(fn);
    if (cached) return cached;

    const bound = new Proxy(fn, {
      apply(target, thisArg, args) {
        const prevPkg = getCurrentPackage();
        if (itemPath) {
          setCurrentPackage(itemPath);
          setCurrentAssets(itemPath);
        }
        try {
          return asyncPackageContext.run({ packagePath: itemPath }, () => {
            return Reflect.apply(target, thisArg, args);
          });
        } finally {
          setCurrentPackage(prevPkg);
          setCurrentAssets(prevPkg);
        }
      },
      construct(target, args, newTarget) {
        const prevPkg = getCurrentPackage();
        if (itemPath) {
          setCurrentPackage(itemPath);
          setCurrentAssets(itemPath);
        }
        try {
          return asyncPackageContext.run({ packagePath: itemPath }, () => {
            return Reflect.construct(target, args, newTarget);
          });
        } finally {
          setCurrentPackage(prevPkg);
          setCurrentAssets(prevPkg);
        }
      },
      get(target, prop, receiver) {
        if (prop === '__pkgBound') return true;
        const val = Reflect.get(target, prop, target);
        if (typeof val === 'function' && prop !== 'constructor' && prop !== 'prototype') {
          return bindPackageFunction(val, itemPath);
        }
        return val;
      },
      set(target, prop, value, receiver) {
        return Reflect.set(target, prop, value, target);
      },
      has(target, prop) {
        return Reflect.has(target, prop);
      }
    });

    boundFunctionCache.set(fn, bound);
    return bound;
  }

  function wrapPackageModule(pkgName, mod) {
    if (!mod || (typeof mod !== 'object' && typeof mod !== 'function')) return mod;
    const itemPath = queuePathByName[pkgName] || ('packages/' + pkgName.replace(/:/g, '_') + '.js');
    if (!packageHasCustomEnv(itemPath)) return mod;
    if (mod.__pkgWrapped) return mod;

    const boundCache = new Map();
    function getBound(fn) {
      if (typeof fn !== 'function' || fn.__pkgBound) return fn;
      let b = boundCache.get(fn);
      if (!b) {
        b = bindPackageFunction(fn, itemPath);
        boundCache.set(fn, b);
      }
      return b;
    }

    const handler = {
      get(target, prop, receiver) {
        if (prop === '__pkgWrapped') return true;
        const val = Reflect.get(target, prop, receiver);
        if (typeof val === 'function' && prop !== 'Promise' && prop !== 'Meteor') {
          return getBound(val);
        }
        return val;
      }
    };

    if (typeof mod === 'function') {
      handler.apply = function (target, thisArg, args) {
        const prevPkg = getCurrentPackage();
        if (itemPath) {
          setCurrentPackage(itemPath);
          setCurrentAssets(itemPath);
        }
        try {
          return asyncPackageContext.run({ packagePath: itemPath }, () => {
            return Reflect.apply(target, thisArg, args);
          });
        } finally {
          setCurrentPackage(prevPkg);
          setCurrentAssets(prevPkg);
        }
      };
    }

    return new Proxy(mod, handler);
  }
  globalThis.__meteorWrapPackageModule = wrapPackageModule;

  const packageGetterBoundCache = new WeakMap();
  globalThis.__meteorWrapPackageGetter = function (modId, getter) {
    let itemPath = null;
    if (typeof modId === 'string' && modId.startsWith('/node_modules/meteor/')) {
      const rest = modId.slice(21);
      const pkgName = rest.split('/')[0];
      itemPath = queuePathByName[pkgName] || ('packages/' + pkgName.replace(/:/g, '_') + '.js');
    }
    if (!itemPath || !packageHasCustomEnv(itemPath)) {
      return getter;
    }

    return function () {
      const val = getter();
      if (typeof val === 'function') {
        if (val.__pkgBound) return val;
        let b = packageGetterBoundCache.get(val);
        if (!b) {
          b = bindPackageFunction(val, itemPath);
          packageGetterBoundCache.set(val, b);
        }
        return b;
      }
      return val;
    };
  };

  let queueWrapped = false;
  function wrapCoreRuntimeQueue() {
    const coreRuntime = globalThis.Package && globalThis.Package['core-runtime'];
    if (!coreRuntime || typeof coreRuntime.queue !== 'function') return false;

    function hookModuleExport() {
      const mr = globalThis.Package && globalThis.Package['modules-runtime'];
      if (mr && mr.meteorInstall && mr.meteorInstall.Module && mr.meteorInstall.Module.prototype) {
        const Mp = mr.meteorInstall.Module.prototype;
        if (typeof Mp.export === 'function' && !Mp.export.__pkgWrapped) {
          const origExport = Mp.export;
          Mp.export = function (getters, constant) {
            if (getters && typeof getters === 'object' && typeof this.id === 'string' && this.id.startsWith('/node_modules/meteor/')) {
              const wrapped = {};
              for (const key of Object.keys(getters)) {
                wrapped[key] = globalThis.__meteorWrapPackageGetter(this.id, getters[key]);
              }
              return origExport.call(this, wrapped, constant);
            }
            return origExport.call(this, getters, constant);
          };
          Mp.export.__pkgWrapped = true;
        }
      }
    }

    const PRp = Object.getPrototypeOf(globalThis.Package);
    if (PRp && typeof PRp._define === 'function' && !PRp._define.__wrapped) {
      const originalDefine = PRp._define;
      PRp._define = function definePackage(name, pkg) {
        hookModuleExport();
        const itemPath = name == null ? null : queuePathByName[name] || null;
        const res = originalDefine.apply(this, arguments);
        hookModuleExport();
        if (itemPath && packageHasCustomEnv(itemPath) && res && typeof res === 'object') {
          for (const key of Object.keys(res)) {
            if (key === 'Promise' || key === 'Meteor') continue;
            const desc = Object.getOwnPropertyDescriptor(res, key);
            if (!desc) continue;
            if (typeof desc.value === 'function' && !desc.value.__pkgBound) {
              try {
                Object.defineProperty(res, key, {
                  value: bindPackageFunction(desc.value, itemPath),
                  writable: desc.writable !== false,
                  configurable: true,
                  enumerable: desc.enumerable,
                });
              } catch {}
            } else if (typeof desc.get === 'function') {
              const origGet = desc.get;
              try {
                Object.defineProperty(res, key, {
                  get() {
                    const fn = origGet.call(this);
                    if (typeof fn === 'function' && !fn.__pkgBound) {
                      return bindPackageFunction(fn, itemPath);
                    }
                    return fn;
                  },
                  configurable: true,
                  enumerable: desc.enumerable,
                });
              } catch {}
            }
          }
        }
        return res;
      };
      PRp._define.__wrapped = true;
    }

    const originalQueue = coreRuntime.queue;
    coreRuntime.queue = function (name, runImage) {
      const itemPath = name == null ? null : queuePathByName[name] || null;
      return originalQueue.call(this, name, function () {
        const prevPkg = getCurrentPackage();
        if (itemPath) {
          setCurrentPackage(itemPath);
          setCurrentAssets(itemPath);
        }
        try {
          return asyncPackageContext.run({ packagePath: itemPath }, function () {
            const targetThis = typeof globalThis !== 'undefined' ? globalThis : this;
            const config = runImage.apply(targetThis, arguments);
            if (config && typeof config.require === 'function') {
              const originalRequire = config.require;
              config.require = function (id) {
                const prevReqPkg = getCurrentPackage();
                if (itemPath) {
                  setCurrentPackage(itemPath);
                  setCurrentAssets(itemPath);
                }
                let res;
                try {
                  res = asyncPackageContext.run({ packagePath: itemPath }, () => {
                    return originalRequire.apply(this, arguments);
                  });
                } finally {
                  setCurrentPackage(prevReqPkg);
                  setCurrentAssets(prevReqPkg);
                }
                if (typeof id === 'string' && id.startsWith('meteor/')) {
                  return wrapPackageModule(id.slice(7), res);
                }
                return res;
              };
            }
            return config;
          });
        } finally {
          setCurrentPackage(prevPkg);
          setCurrentAssets(prevPkg);
        }
      });
    };
    return true;
  }

  // Import all packages in the dependency order computed by isobuild
  for (const item of programJson.load) {
    setCurrentPackage(item.path);
    setCurrentAssets(item.path);
    await asyncPackageContext.run({ packagePath: item.path }, async function () {
      await import(pathToFileURL(path.join(serverDir, item.path)).href);
    });
    // core-runtime loads first; wrap its queue before any package registers.
    if (!queueWrapped) queueWrapped = wrapCoreRuntimeQueue();
  }

  // Wait for core-runtime async queue (deferred package initialization)
  const ready = globalThis.Package['core-runtime'].waitUntilAllLoaded();
  if (ready) await ready;

  // Startup hooks and main() belong to the app, not to whichever package
  // happened to initialize last.
  if (appPath) {
    setCurrentPackage(appPath);
    setCurrentAssets(appPath);
  }

  return { serverDir, programJson, configJson };
}

/**
 * Run startup hooks and main(). Call after bootPackages().
 */
export async function runMain() {
  while (globalThis.__meteor_bootstrap__.startupHooks.length) {
    await globalThis.__meteor_bootstrap__.startupHooks.shift()();
  }
  globalThis.__meteor_bootstrap__.startupHooks = null;

  // Find and run main()
  const mains = [];
  if ('main' in globalThis) mains.push(globalThis.main);
  if (typeof Package !== 'undefined') {
    for (const name of Object.keys(Package)) {
      const { main } = Package[name];
      if (typeof main === 'function' && !mains.includes(main)) mains.push(main);
    }
  }

  if (mains.length === 1) {
    const exitCode = await mains[0].call({}, process.argv.slice(2));
    if (exitCode !== 'DAEMON') process.exit(exitCode);
  } else if (mains.length === 0) {
    console.error('No main() function found.');
    process.exit(1);
  }
}

/**
 * Full boot: load packages + run main. Backward compatible entry point.
 * Used by index.mjs generated by the bundler.
 */
export async function boot(serverDir) {
  const ctx = await bootPackages(serverDir);
  await runMain();
  return ctx;
}
