// ESM Loader for Meteor server bundles
//
// Alternative to the legacy boot chain (boot.js + runtime.js + npm-require.js).
// Loads Meteor packages via standard ESM dynamic imports instead of
// vm.runInThisContext, eliminating the need for Reify and Module.prototype
// patching.
//
// Generated by `meteor build --format=esm`. Not used by the legacy format.
//
// Usage:
//   import { boot } from './esm-loader.mjs';
//   await boot('/path/to/bundle/programs/server');

import { createRequire } from 'node:module';
import { AsyncLocalStorage } from 'node:async_hooks';
import path from 'node:path';
import fs from 'node:fs';

// ============================================================
// Resolver
//
// Maps npm require calls from Meteor packages to their actual
// locations on disk. Each package may have its own node_modules
// directory; the resolver uses program.json to build a per-package
// search path.
// ============================================================

function createResolver(serverDir, programJson) {
  const require = createRequire(path.join(serverDir, '_virtual.js'));

  const packageNodeModulesMap = {};
  for (const item of programJson.load) {
    const dirs = [];
    if (typeof item.node_modules === 'string') {
      dirs.push(path.join(serverDir, item.node_modules));
    } else if (item.node_modules && typeof item.node_modules === 'object') {
      for (const p of Object.keys(item.node_modules)) {
        if (!item.node_modules[p].local) dirs.push(path.join(serverDir, p));
      }
    }
    dirs.push(path.join(serverDir, 'node_modules'));
    packageNodeModulesMap[item.path] = dirs;
  }

  let currentPackagePath = null;

  function resolveInDirs(name, dirs) {
    for (const dir of dirs) {
      try {
        return createRequire(path.join(dir, '_v.js')).resolve(name);
      } catch (e) { continue; }
    }
    return null;
  }

  function getDirs() {
    return currentPackagePath
      ? (packageNodeModulesMap[currentPackagePath] || [path.join(serverDir, 'node_modules')])
      : [path.join(serverDir, 'node_modules')];
  }

  function meteorNpmRequire(name, error) {
    const dirs = getDirs();

    // Virtual absolute paths: /node_modules/meteor/X/node_modules/Y
    if (name.startsWith('/node_modules/')) {
      const parts = name.split('/node_modules/');
      const lastPart = parts[parts.length - 1];
      const resolved = resolveInDirs(lastPart, dirs);
      if (resolved) return require(resolved);
      const diskPath = path.join(serverDir, 'npm' + name);
      if (fs.existsSync(diskPath)) return require(diskPath);
    }

    // Normal module names
    const resolved = resolveInDirs(name, dirs);
    if (resolved) return require(resolved);

    // Node builtins
    try { return require(name); } catch (e) {}

    throw error || new Error('Cannot find module ' + JSON.stringify(name));
  }

  meteorNpmRequire.resolve = function (name) {
    const dirs = getDirs();
    if (name.startsWith('/node_modules/')) {
      const parts = name.split('/node_modules/');
      const lastPart = parts[parts.length - 1];
      const resolved = resolveInDirs(lastPart, dirs);
      if (resolved) return resolved;
      const diskPath = path.join(serverDir, 'npm' + name);
      if (fs.existsSync(diskPath)) return diskPath;
    }
    const resolved = resolveInDirs(name, dirs);
    if (resolved) return resolved;
    return require.resolve(name);
  };

  return { meteorNpmRequire, setCurrentPackage(p) { currentPackagePath = p; } };
}

// ============================================================
// Boot
//
// Sets up globals, imports all Meteor packages in dependency
// order, runs startup hooks, and calls main().
// ============================================================

export async function boot(serverDir) {
  const programJson = JSON.parse(fs.readFileSync(path.join(serverDir, 'program.json'), 'utf8'));
  const configJson = JSON.parse(fs.readFileSync(path.join(serverDir, 'config.json'), 'utf8'));
  const buildDir = path.dirname(path.dirname(serverDir));
  const starJson = JSON.parse(fs.readFileSync(path.join(buildDir, 'star.json'), 'utf8'));
  const programsDir = path.dirname(serverDir);

  const { meteorNpmRequire, setCurrentPackage } = createResolver(serverDir, programJson);

  // Build per-package asset maps from program.json
  // In the legacy boot, Assets is injected per-package via closure.
  // Here, we use a global Assets object that switches context per-package,
  // same pattern as the resolver's setCurrentPackage.
  const packageAssetsMap = {};
  for (const item of programJson.load) {
    if (item.assets) {
      packageAssetsMap[item.path] = item.assets;
    }
  }
  let currentAssets = null;

  function setCurrentAssets(packagePath) {
    currentAssets = packageAssetsMap[packagePath] || null;
  }

  // Path normalization matching boot.js behavior (via mini-files.ts)
  function normalizeAssetPath(assetPath) {
    if (process.platform === 'win32') {
      assetPath = assetPath.replace(/\\/g, '/');
    }
    return assetPath ? assetPath.normalize('NFC') : assetPath;
  }

  // Globals expected by Meteor packages
  globalThis.__meteor_bootstrap__ = {
    startupHooks: [],
    serverDir,
    configJson,
    isFibersDisabled: true,
  };
  globalThis.__meteor_runtime_config__ = {
    meteorRelease: configJson.meteorRelease,
    gitCommitHash: starJson.gitCommitHash,
  };
  if (!process.env.APP_ID) process.env.APP_ID = configJson.appId;

  globalThis.Npm = { require: meteorNpmRequire };

  // Assets API — reads real files from the bundle, per-package context
  globalThis.Assets = {
    getTextAsync(assetPath, callback) {
      return getAsset(assetPath, 'utf8', callback);
    },
    getBinaryAsync(assetPath, callback) {
      return getAsset(assetPath, undefined, callback);
    },
    absoluteFilePath(assetPath) {
      assetPath = normalizeAssetPath(assetPath);
      if (!currentAssets || !currentAssets[assetPath]) {
        throw new Error('Unknown asset: ' + assetPath);
      }
      return path.join(serverDir, currentAssets[assetPath]);
    },
    getServerDir() { return serverDir; },
  };

  function getAsset(assetPath, encoding, callback) {
    assetPath = normalizeAssetPath(assetPath);
    if (!currentAssets || !currentAssets[assetPath]) {
      const err = new Error('Unknown asset: ' + assetPath);
      if (callback) { callback(err); return; }
      return Promise.reject(err);
    }
    const filePath = path.join(serverDir, currentAssets[assetPath]);
    if (callback) {
      fs.readFile(filePath, encoding, (err, result) => {
        if (err) { callback(err); return; }
        callback(null, encoding ? result : new Uint8Array(result));
      });
      return;
    }
    return fs.promises.readFile(filePath, encoding).then(result =>
      encoding ? result : new Uint8Array(result)
    );
  }

  globalThis.npmRequire = meteorNpmRequire;
  globalThis.Profile = function (name, fn) { return fn || function () {}; };
  globalThis.Profile.time = function (name, fn) { return fn(); };
  globalThis.Profile.run = async function (name, fn) { return fn(); };

  globalThis.__METEOR_ASYNC_LOCAL_STORAGE = new AsyncLocalStorage();

  // Enable native source maps (Node 20+)
  if (typeof process.setSourceMapsEnabled === 'function') {
    process.setSourceMapsEnabled(true);
  }

  // Dynamic import info for the dynamic-import package
  globalThis.dynamicImportInfo = { server: { dynamicRoot: path.join(serverDir, 'dynamic') } };
  const clientArchs = configJson.clientArchs || Object.keys(configJson.clientPaths || {});
  clientArchs.forEach(arch => {
    globalThis.dynamicImportInfo[arch] = { dynamicRoot: path.join(programsDir, arch, 'dynamic') };
  });

  // The Meteor linker generates implicit global assignments
  // (e.g. `Mongo = Package.mongo.Mongo`) which are illegal in ESM strict mode.
  // Pre-declare them on globalThis to avoid ReferenceError.
  for (const dir of [path.join(serverDir, 'packages'), path.join(serverDir, 'app')]) {
    if (!fs.existsSync(dir)) continue;
    for (const file of fs.readdirSync(dir).filter(f => f.endsWith('.js'))) {
      const src = fs.readFileSync(path.join(dir, file), 'utf8');
      for (const m of src.matchAll(/^(\w+)\s*=\s*Package/gm)) {
        if (!(m[1] in globalThis)) globalThis[m[1]] = undefined;
      }
    }
  }

  // Import all packages in the dependency order computed by isobuild
  for (const item of programJson.load) {
    setCurrentPackage(item.path);
    setCurrentAssets(item.path);
    await import(path.join(serverDir, item.path));
  }

  // Wait for core-runtime async queue (deferred package initialization)
  const ready = globalThis.Package['core-runtime'].waitUntilAllLoaded();
  if (ready) await ready;

  // Run startup hooks
  while (globalThis.__meteor_bootstrap__.startupHooks.length) {
    await globalThis.__meteor_bootstrap__.startupHooks.shift()();
  }
  globalThis.__meteor_bootstrap__.startupHooks = null;

  // Find and run main()
  const mains = [];
  if ('main' in globalThis) mains.push(globalThis.main);
  if (typeof Package !== 'undefined') {
    for (const name of Object.keys(Package)) {
      const { main } = Package[name];
      if (typeof main === 'function' && !mains.includes(main)) mains.push(main);
    }
  }

  if (mains.length === 1) {
    const exitCode = await mains[0].call({}, process.argv.slice(2));
    if (exitCode !== 'DAEMON') process.exit(exitCode);
  } else if (mains.length === 0) {
    console.error('No main() function found.');
    process.exit(1);
  }

  return { serverDir, programJson, configJson };
}
