// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "3.7"
#define szVerMajorMinorBuildRev "3.7.5534.8992"
#define rmj	3
#define rmm	7
#define rbd	5534
#define rev	8992
#define szVerName	"BalExtensionExt Release"

#endif
