Document: meteor
Title: Debian meteor Manual
Author: <insert document author here>
Abstract: This manual describes what meteor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/meteor/meteor.sgml.gz

Format: postscript
Files: /usr/share/doc/meteor/meteor.ps.gz

Format: text
Files: /usr/share/doc/meteor/meteor.text.gz

Format: HTML
Index: /usr/share/doc/meteor/html/index.html
Files: /usr/share/doc/meteor/html/*.html
