import { Meteor } from 'meteor/meteor';
import { Accounts } from 'meteor/accounts-base';
import { transformSelector, withCallback } from './util.js';
import { requestAssertion, callLoginMethod } from './orchestration.js';

/**
 * @summary Log the user in with a password and a security key. Returns a Promise.
 * Use it after `Meteor.loginWithPasswordAsync` failed with the
 * `no-webauthn-assertion` error.
 * @locus Client
 * @param {Object | String} selector
 *   Either a string interpreted as a username or an email; or an object with a
 *   single key: `email`, `username` or `id`.
 * @param {String} password The user's password.
 * @returns {Promise<Object>} Resolves with login details on success, rejects with error on failure.
 * @importFromPackage meteor
 */
Meteor.loginWithPasswordAndWebAuthnAsync = async (selector, password) => {
  if (typeof Accounts._hashPassword !== 'function') {
    throw new Meteor.Error(
      400,
      'loginWithPasswordAndWebAuthn requires the accounts-password package'
    );
  }
  if (typeof password !== 'string') {
    throw new Meteor.Error(400, 'Password must be a string');
  }
  const user = transformSelector(selector);
  const webauthn = await requestAssertion({ selector: user, mode: 'secondFactor' });
  return callLoginMethod([
    { user, password: Accounts._hashPassword(password), webauthn },
  ]);
};

/**
 * @summary Log the user in with a password and a security key. Use it after
 * `Meteor.loginWithPassword` failed with the `no-webauthn-assertion` error.
 * @locus Client
 * @param {Object | String} selector
 *   Either a string interpreted as a username or an email; or an object with a
 *   single key: `email`, `username` or `id`.
 * @param {String} password The user's password.
 * @param {Function} [callback] Optional callback.
 *   Called with no arguments on success, or with a single `Error` argument
 *   on failure.
 * @importFromPackage meteor
 */
Meteor.loginWithPasswordAndWebAuthn = withCallback(
  Meteor.loginWithPasswordAndWebAuthnAsync
);

/**
 * @summary Log the user in with a one time token and a security key. Returns a Promise.
 * Use it after `Meteor.passwordlessLoginWithToken` failed with the
 * `no-webauthn-assertion` error.
 * @locus Client
 * @param {Object | String} selector Username, email or custom selector to identify the user.
 * @param {String} token one time token generated by the server
 * @returns {Promise<Object>} Resolves with login details on success, rejects with error on failure.
 * @importFromPackage meteor
 */
Meteor.passwordlessLoginWithTokenAndWebAuthnAsync = async (selector, token) => {
  if (typeof token !== 'string' || !token) {
    throw new Meteor.Error(400, 'Token must be a non-empty string');
  }
  const normalizedSelector = transformSelector(selector);
  const webauthn = await requestAssertion({
    selector: normalizedSelector,
    mode: 'secondFactor',
  });
  return callLoginMethod([{ selector: normalizedSelector, token, webauthn }]);
};

/**
 * @summary Log the user in with a one time token and a security key. Use it
 * after `Meteor.passwordlessLoginWithToken` failed with the
 * `no-webauthn-assertion` error.
 * @locus Client
 * @param {Object | String} selector Username, email or custom selector to identify the user.
 * @param {String} token one time token generated by the server
 * @param {Function} [callback] Optional callback.
 *   Called with no arguments on success, or with a single `Error` argument
 *   on failure.
 * @importFromPackage meteor
 */
Meteor.passwordlessLoginWithTokenAndWebAuthn = withCallback(
  Meteor.passwordlessLoginWithTokenAndWebAuthnAsync
);
