(function () {
  // Open a popup window pointing to a OAuth1 handshake page
  //
  // @param state {String} The OAuth1 state generated by the client
  // @param url {String} url to page
  Meteor.accounts.oauth1.initiateLogin = function(state, url) {
    // Include the oauth version as the last parameter
    Meteor.accounts.oauth.initiateLogin(state, url, 1);
  };
})();