name: Check legacy syntax
on:
  - pull_request
permissions:
  contents: read

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
      - run: cd scripts/admin/check-legacy-syntax && npm ci
      - name: Check syntax
        run: cd scripts/admin/check-legacy-syntax && node check-syntax.js
