name: Check code-style
on:
  push:
    paths:
      - 'packages/**'
      - 'npm-packages/meteor-installer/**'
  pull_request:
    paths:
      - 'packages/**'
      - 'npm-packages/meteor-installer/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  check-code-style:
    runs-on: oss-vm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24.x
      - run: npm ci
      - name: Check formatting with oxfmt
        run: npx oxfmt --ignore-path .fmtignore --check .
      - name: Run lint with oxlint
        run: npm run lint
