name: Meteor Docs PR
on:
  pull_request:
    paths:
      - 'docs/**/*'
jobs:
  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Build the Docs
        run: npm ci && npm run build
      - name: Deploy to Netlify for preview
        uses: nwtgck/actions-netlify@v1.2.4
        with:
          publish-dir: './docs/public/'
          production-branch: devel
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Deploy from GitHub Actions ${{ github.event.pull_request.title }}
          netlify-config-path: './docs/netlify.toml'
          alias: deploy-preview-${{ github.event.number }}
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DOCS_SITE_ID }}
