name: Meteor Docs PR
on:
  pull_request:
    paths:
      - 'docs/**/*'
jobs:
  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 12.x
      - name: Build the Docs
        run: npm ci && npm run build
      - name: Deploy to Netlify for preview
        uses: nwtgck/actions-netlify@7a92f00dde8c92a5a9e8385ec2919775f7647352 # v2.1.0
        with:
          publish-dir: './docs/public/'
          production-branch: devel
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Deploy from GitHub Actions ${{ github.event.pull_request.title }}
          netlify-config-path: './docs/netlify.toml'
          alias: deploy-preview-${{ github.event.number }}
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DOCS_SITE_ID }}
