name: Inactive Issues Management

on:
  schedule:
    # “At 01:00 on Saturday.”
    - cron: '0 1 * * 6'
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  manage-inactive-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      
      - name: Manage inactive issues
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const script = require('./.github/scripts/inactive-issues.js')
            await script({github, context})
