name: Inactive Issues Management

on:
  schedule:
    # “At 01:00 on Saturday.”
    - cron: '0 1 * * 6'
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  manage-inactive-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      
      - name: Manage inactive issues
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const script = require('./.github/scripts/inactive-issues.js')
            await script({github, context})
