# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  - pull_request_target

permissions:
  contents: read  #  to determine modified files (actions/labeler)
  pull-requests: write  #  to add labels to PRs (actions/labeler)

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
