name: NPM meteor-babel
on:
  push:
    paths:
      - "npm-packages/meteor-babel/**"
  pull_request:
    paths:
      - "npm-packages/meteor-babel/**"

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: npm-packages/meteor-babel
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 14.x
          cache: npm
      - run: npm ci
      - run: npm run test
