name: NPM meteor-babel
on:
  push:
    paths:
      - "npm-packages/meteor-babel/**"
  pull_request:
    paths:
      - "npm-packages/meteor-babel/**"

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: npm-packages/meteor-babel
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 14.x
          cache: npm
      - run: npm ci
      - run: npm run test
