name: Run Profiler

on:
  issue_comment:
    types: [created]

jobs:
  run-profiler:
    if: github.event.issue.pull_request && contains(github.event.comment.body , '/profile')
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x

      - name: Set ENVs
        run: |
          value="VALUE"
          echo "Key=$value" >> $GITHUB_ENV

          PR_NUMBER="${{ github.event.issue.number }}"
          echo "PrNumber=$PR_NUMBER" >> $GITHUB_ENV

      - name: Run CI
        run: |
          echo "Running meteor profiler..."
          echo $PR_NUMBER
          git status
          ls

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@65f9e5c9a1f2cd378bd74b2e057c9736982a8e74 # v3
        with:
          message: |
            Hello world !!!! :wave:
            this is pr number: #${{ env.PrNumber }}
            testing value: ${{ env.Key }}
          pr-number: ${{ github.event.issue.number }}
