name: Test DDP Transports

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-ddp-transport:
    strategy:
      fail-fast: false
      matrix:
        transport:
          - 'sockjs'
          - 'uws'
    runs-on: oss-vm
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.transport }}
      cancel-in-progress: true
    timeout-minutes: 30
    env:
      CXX: g++-12
      phantom: false
      PUPPETEER_DOWNLOAD_PATH: /home/runner/.npm/chromium
      TEST_PACKAGES_EXCLUDE: stylus
      METEOR_MODERN: true
      NODE_ENV: CI
      DDP_TRANSPORT: ${{ matrix.transport }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24.15.0

      - name: Restore caches
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.npm
            .meteor
            .babel-cache
            dev_bundle
            /home/runner/.npm/chromium
          key: ${{ runner.os }}-node-24-${{ hashFiles('meteor', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-24-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-12 libnss3

      - name: Install npm dependencies
        run: npm install

      - name: Run DDP server tests (${{ matrix.transport }})
        run: ./packages/test-in-console/run.sh "ddp-server"
