name: Test Deprecated Packages

# Disabled until we figure out how to fix the error from puppeteer
# Runs on Travis CI for now
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-test-deprecated-packages
      cancel-in-progress: true
    timeout-minutes: 60

    env:
      PUPPETEER_DOWNLOAD_PATH: /home/runner/.npm/chromium

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Update and install dependencies
        run: sudo apt-get update && sudo apt-get install -y libnss3 g++-12

      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 20.15.1

      - name: Cache Node.js modules
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: |
            ~/.npm
            .meteor
            .babel-cache
            dev_bundle
            /home/runner/.npm/chromium
          key: ${{ runner.os }}-node-${{ hashFiles('meteor', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: ./packages/test-in-console/run.sh