name: Type Coverage
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  type-coverage:
    runs-on: oss-vm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - name: Type compilation
        run: npm run types:compile
      - name: Type tests
        run: npm run types:test
      - name: Type coverage (99%)
        run: npm run types:coverage
      - name: Type test coverage (100%)
        run: npm run types:dts-test-coverage
