name: Type Coverage
on:
  - pull_request
jobs:
  type-coverage:
    runs-on: oss-vm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - name: Type compilation 
        run: npm run types:compile
      - name: Type coverage (99%)
        run: npm run types:coverage
      - name: Type test coverage
        run: |
          # replace by a npm pkg
          cd scripts/check-type-test-coverage
          npm ci
          node index.js ../../packages
